Option = function(fieldName, value, name, html) {
  var self = this;
  self.fieldName = fieldName;
  self.value = value;
  if (name == null) {
    self.name = _.str.titleize( replaceAll('-',' ', self.value) );
  } else {
    self.name = name;
  }
  self.html = html || self.name;
};
allOptions = [
  new Option('respondingTo', 'none'),
  new Option('respondingTo', 'nightsafe', 'NightSafe'),
  new Option('respondingTo', 'city-safe'),
  new Option('respondingTo', 'venue'),
  new Option('respondingTo', 'police'),
  new Option('respondingTo', 'taxi'),
  new Option('respondingTo', 'ambulance'),
  new Option('respondingTo', 'public'),
  new Option('respondingTo', 'other'),
  new Option('liquorAccordPrecinct', 'valley'),
  new Option('liquorAccordPrecinct', 'cbd', 'CBD'),
  new Option('liquorAccordPrecinct', 'caxton-street', 'Caxton St'),
  new Option('liquorAccordPrecinct', 'west-end', 'West End'),
  new Option('liquorAccordPrecinct', 'other'),
  new Option('setting', 'public-footpath', 'Public Space (Footpath)'),
  new Option('setting', 'public-mall', 'Public Space (Mall)'),
  new Option('setting', 'public-roadway', 'Public Space (Roadway)'),
  new Option('setting', 'public-park-common', 'Public Space (Park or Common)'),
  new Option('setting', 'venue-inside', 'Venue (Inside)'),
  new Option('setting', 'venue-outside', 'Venue (Outside)'),
  new Option('setting', 'taxi-rank', 'Taxi Rank'),
  new Option('setting', 'police-station', 'Police Station'),
  new Option('setting', 'other'),
  new Option('type', 'first-aid', 'First Aid', '<i class="fa fa-medkit fa-fw"></i> First Aid'),
  new Option('type', 'diversion', 'Diversion', '<i class="fa fa-bullhorn fa-fw"></i> Diversion'),
  new Option('type', 'support', 'Support', '<i class="fa fa-shield fa-fw"></i> Support'),
  new Option('type', 'advice', 'Advice', '<i class="fa fa-comments-o fa-fw"></i> Advice'),
  new Option('type', 'transport', 'Transport', '<i class="fa fa-truck fa-fw"></i> Transport'),
  new Option('type', 'non-service', 'GoA/ Non-Service', '<i class="fa fa-times-circle fa-fw"></i> GoA / Non-Service'),
  new Option('ageBracket', '-17', '-17'),
  new Option('ageBracket', '18-21', '18-21'),
  new Option('ageBracket', '22-25', '22-25'),
  new Option('ageBracket', '26-29', '26-29'),
  new Option('ageBracket', '30-34', '30-34'),
  new Option('ageBracket', '35-39', '35-39'),
  new Option('ageBracket', '40+', '40+'),
  new Option('gender', 'male', 'Male', '<i class="fa fa-male fa-fw"></i> Male'),
  new Option('gender', 'female', 'Female', '<i class="fa fa-male fa-fw"></i> Female'),
  new Option('culturalBackground', 'resident'),
  new Option('culturalBackground', 'non-resident', 'Non-Resident'),
  new Option('culturalBackground', 'atsi', 'ATSI'),
  new Option('culturalBackground', 'homeless', 'Homeless'),
  new Option('culturalBackground', 'cultural-linquistic', 'Cultural / Ling...'),
  new Option('conditionType', 'alchohol-intoxication-primary', 'Alchohol Intoxication - Primary'),
  new Option('conditionType', 'drugs-primary', 'Drugs - Primary'),
  new Option('conditionType', 'injury-accident', 'Injury by Accident'),
  new Option('conditionType', 'injury-assault', 'Injury by Assault'),
  new Option('conditionType', 'injury-self-harm', 'Injury by Self Harm'),
  new Option('conditionType', 'medical-condition', 'Medical Condition'),
  new Option('conditionType', 'mental-health-issues', 'Mental Health Issues'),
  new Option('conditionType', 'distress'),
  new Option('conditionType', 'unknown'),
  new Option('conditionType', 'other'),
  new Option(
    'conditionRating',
    '1-appropriate',
    '1 - Appropriate',
    '&#9312; Appropriate <small>(Basic First Aid)</small>'
    ),
  new Option(
    'conditionRating',
    '2-satisfactory',
    '2 - Satisfactory',
    '&#9313; Satisfactory <small>(First Aid plus Advised to seek early Medical Advice)</small>'
    ),
  new Option(
    'conditionRating',
    '3-stable',
    '3 - Stable',
    '&#9314; Stable <small>(Transported to Hospital/medical NightSafe)</small>'
    ),
  new Option(
    'conditionRating',
    '4-serious',
    '4 - Serious',
    '&#9315; Critical <small>(QAS called to attend and/or transport to hospital)</small>'
    ),
  new Option(
    'conditionRating',
    '5-critical',
    '5 - Critical',
    '&#9316; Critical <small>(Life Threatening - QAS to Hospital)</small>'
    ),
  new Option('transportedTo', 'none'),
  new Option('transportedTo', 'home-or-friends-place', 'Home or Friend&apos;s Place'),
  //This might be an issue in future as this fieldName is used in two places & in the first, home is not needed
  new Option('transportedTo', 'nightsafe', 'NightSafe'),
  new Option('transportedTo', 'royal-brisbane-hospital'),
  new Option('transportedTo', 'mater-hospital'),
  new Option('transportedTo', 'princes-alexanders-hospital'),
  new Option('transportedTo', 'private-hospital'),
  new Option('transportedTo', 'other'),
  new Option('diversionType', 'assault-in-progress', 'Assault in Progress'),
  new Option('diversionType', 'conflict-intervention'),
  new Option('diversionType', 'personal-safety'),
  new Option('diversionType', 'self-harm-or-ideation', 'Self Harm or Ideation'),
  new Option('diversionType', 'other'),
  new Option('supportGivenTo', 'ambulance'),
  new Option('supportGivenTo', 'police'),
  new Option('supportGivenTo', 'taxi'),
  new Option('supportGivenTo', 'venue'),
  new Option('supportGivenTo', 'public'),
  new Option('adviceGivenTo', 'general-advice'),
  new Option('adviceGivenTo', 'personal-safety'),
  new Option('adviceGivenTo', 'safe-drinking'),
  new Option('adviceGivenTo', 'directions'),
  new Option('adviceGivenTo', 'transport'),
  new Option('adviceGivenTo', 'other'),
  new Option('transportConditionType', 'medical'),
  new Option('transportConditionType', 'intox'),
  new Option('transportConditionType', 'mental-health'),
  new Option('transportConditionType', 'distress'),
  new Option('transportConditionType', 'saftey'),
  new Option('transportConditionType', 'other'),
  new Option('nonServiceType', 'gone-on-arrival', 'Gone on Arrival'),
  new Option('nonServiceType', 'assistance-not-required', 'Assistance not Required'),
  new Option('nonServiceType', 'assistance-refused'),
  new Option('nonServiceType', 'other'),
  new Option('durationHours', 0, '0'),
  new Option('durationHours', 1, '1'),
  new Option('durationHours', 2, '2'),
  new Option('durationHours', 3, '3'),
  new Option('durationHours', 4, '4'),
  new Option('durationHours', 5, '5'),
  new Option('durationMinutes', 0, '0'),
  new Option('durationMinutes', 15, '15'),
  new Option('durationMinutes', 30, '30'),
  new Option('durationMinutes', 45, '45'),
];